name: vibe_rise
description: VibeRise — BLE-controlled vibration alarm demo
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"   # matches your Dart 3.8.x toolchain

dependencies:
  flutter:
    sdk: flutter

  # BLE + permissions
  flutter_blue_plus: ^1.35.5
  flutter_reactive_ble: ^5.4.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Icon generator (run manually; safe to keep here)
  flutter_launcher_icons: ^0.13.1

# Configure launcher icons (adjust paths/colors to your assets before running)
flutter_launcher_icons:
  android: true
  image_path: assets/icon.png
  adaptive_icon_foreground: assets/icon_foreground.png
  adaptive_icon_background: assets/icon_background.png

flutter:
  uses-material-design: true
  # If you keep app assets, list them here (optional):
  # assets:
  #   - assets/
